name: Automerge
on: [pull_request]
jobs:
  automerge:
    runs-on: ubuntu-20.04
    steps:
      - name: Automerge Dependabot
        uses: ridedott/merge-me-action@v2.10.36
        with:
          GITHUB_LOGIN: dependabot[bot]
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_RUN }}
          MERGE_METHOD: REBASE
          PRESET: DEPENDABOT_PATCH